export enum EditorAction {
  OptionImageUpload = 'optionImageUpload',
  OptionAdd = 'optionAdd',
  OptionSave = 'optionSave',
  OptionReorder = 'optionReorder',
  OptionOther = 'optionOther',
  OptionDelete = 'optionDelete',
  FieldChange = 'fieldChange',
  FieldAdd = 'fieldAdd',
  FieldDuplicate = 'fieldDuplicate',
  FieldDelete = 'fieldDelete',
  ImageUpload = 'imageUpload',
  FileUpload = 'fileUpload',
  FieldReorder = 'fieldReorder',
}
